# Generated by Django 5.2.1 on 2026-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_aboutsection_alter_quiz_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-datetime'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Выберите подразделения. Если ничего не выбрано — рассылка уйдет ВСЕМ активным сотрудникам.', to='panel.department', verbose_name='Подразделения'),
        ),
    ]
