# Generated by Django 5.2.1 on 2026-01-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_mailing_options_mailing_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_on_btn', models.CharField(max_length=30, verbose_name='Текст на кнопке')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка в кнопке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли кнопка')),
            ],
            options={
                'verbose_name': 'Кнопки "Помощь"',
                'verbose_name_plural': 'Кнопка "Помощь"',
            },
        ),
        migrations.CreateModel(
            name='HelpPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_on_message', models.TextField(verbose_name='Текст на сообщении с кнопками')),
            ],
            options={
                'verbose_name': 'Главный текст "Помощь"',
                'verbose_name_plural': 'Главный текст "Помощь"',
            },
        ),
    ]
